name: update

on: push

permissions:
  content: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: action/checkout@v3
      - name: Update README.md
        run: |
          echo "# My-Linux-Setup\nSetting up Debian Linux desktop with KDE. Not really much, just what I'll usually install. If you have any reccomendations or something feel free to suggest a change.\n\n```sh\n$(cat setup.sh)\n```\n" > README.md
      - uses: stefanzweifel/git-auto-commit-action@v4
          
      
